

service: cloud
frameworkVersion: "3"
custom:
  config: ${file(config/${opt:stage, 'dev'}.yml)}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:ReceiveMessage"
        - "sqs:DeleteMessage"
        - "sqs:GetQueueAttributes"
      Resource: ${self:custom.config.SQS_NEW_ORDER_ARN}
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource:
        - ${self:custom.config.SNS_NEW_ORDER_ARN}
  environment:
    ENV: ${self:custom.config.ENV}

functions:
  persist:
    handler: handler.persist
    timeout: 20
    events:
      - sqs:
          arn: ${self:custom.config.SQS_NEW_ORDER_ARN}
          batchSize: 10
      - http:
          method: GET
          path: hello
  publish:
    handler: SNS.publish
    events:
      - http:
          method: POST
          path: SNS
